## User Roles [/users/{username}/roles{?roles}]

+ Parameters
	+ username

## Get User Roles [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200 (application/json)

		{
			"message": "Successfully retrieved roles.",
			"roles": [
				{
					"id": 5,
					"name": "user",
					"slug": "user",
					"color": null,
					"songRequests": 0,
					"enabled": false,
					"userRole": {
						"userId": 1,
						"roleId": 5
					}
				},
				...
			]
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 404 (application/json)

		{
			"message": "No user found."
		}

## Update User Roles [PUT]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

	+ Body

			{
				"roles": ["idol"]
			}

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "No body provided."
		}

		{
			"message": "Invalid body provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

## Delete User Roles [DELETE]

+ Parameters
	+ roles (Array<string>)

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

	+ Body

			{
				"roles": ["idol"]
			}

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "No query provided."
		}

		{
			"message": "Invalid query provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

		{
			"message": "Cannot remove admin role."
		}
