FORMAT: 1A

# LISTEN.moe API

:::note
This is a pre-release version of the API. Everything is subject to change.
:::

## Group Entry

<!-- include(routes/home.apib) -->

## Group Account

<!-- include(routes/register.apib) -->
<!-- include(routes/login.apib) -->

## Group Songs Collection

<!-- include(routes/song.apib) -->

## Group Favorites

<!-- include(routes/favorite.apib) -->

## Group Requests Collection

<!-- include(routes/request.apib) -->

## Group Artists Collection

<!-- include(routes/artist.apib) -->

## Group Users Collection

<!-- include(routes/user.apib) -->

## Group Reports

<!-- include(routes/report.apib) -->
