## User 2FA [/users/{username}/mfa{?token}]

+ Parameters
	+ username

## Get User 2FA [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200 (application/json)

		{
			"otpauthURL": "base64 encoded QR image"
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "MFA already activated."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

## Enable User 2FA [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

	+ Body

			{
				"roles": ["idol"]
			}

+ Response 200 (application/json)

		{
			"message": "Successfully enabled mfa. You will now be logged out."
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "No body provided."
		}

		{
			"message": "Invalid body provided."
		}

		{
			"message": "MFA already activated."
		}

+ Response 401 (application/json)

		{
			"message": "Invalid OTP provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

## Disable User 2FA [DELETE]

+ Parameters
	+ token

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200

		{
			"message": "Successfully disabled mfa. You will now be logged out."
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "No query provided."
		}

		{
			"message": "Invalid query provided."
		}

		{
			"message": "No MFA activated."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}
