## Comment [/comments/{id}]

+ Parameters
	+ id

## Get Comment [GET]

+ Response 200 (application/json)

		{
			"message": "Successfully retrieved comment.",
			"comment": {
				"id": 1,
				"parentId": 0,
				"content": "some-content",
				"createdAt": "1970-01-01T00:00:00.000Z",
				"editedAt": "1970-01-01T00:00:00.000Z",
				"user": {
					"uuid": "345c45aa-5h76-9zh4-6tr7-6tkl52rn5783",
					"username": "testuser",
					"displayName": "TestUser",
					"avatarImage": "testuser-512x512.jpg"
				}
			}
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

+ Response 404 (application/json)

		{
			"message": "No comment found."
		}

## Edit Comment [PATCH]


+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

	+ Body

			{
				"content": "new-content"
			}

+ Response 200 (application/json)

		{
			"message": "Successfully updated comment.",
			"comment": {
				"id": 1,
				"parentId": 0,
				"content": "some-content",
				"createdAt": "1970-01-01T00:00:00.000Z",
				"editedAt": "1970-01-01T00:00:00.000Z",
				"user": {
					"uuid": "345c45aa-5h76-9zh4-6tr7-6tkl52rn5783",
					"username": "testuser",
					"displayName": "TestUser",
					"avatarImage": "testuser-512x512.jpg"
				}
			}
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "No body provided."
		}

		{
			"message": "Invalid body provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 404 (application/json)

		{
			"message": "No comment found."
		}
