## Artist [/artists]

## Get Artists [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vdn.listen.v4+json
			Authorization: Bearer JWT

+ Response 200 (application/json)

		{
			"message": "Successfully retrieved all artists.",
			"artists": [
				{
					"id": 1,
					"image": null,
					"name": "Aiobahn",
					"nameRomaji": null,
					"releaseCount": 1,
					"slug": "Aiobahn",
					"songCount": 9
				},
				...
			]
		}

<!-- include(artist/_id.apib) -->
