## Login [/login]

## Login [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json

	+ Body

			{
				"username": "TestUser",
				"password": "superSecurePassword"
			}

			{
				"username": "testUser@gmail.com",
				"password": "superSecurePassword"
			}

+ Response 200 (application/json)

		{
			"message": "Successfully logged in.",
			"token": "JWT",
			"apiKey": "your-api-key" // Only if requested via developer access
		}

		{
			"message": "Please provide the 2FA code to log in.",
			"mfa": true,
			"token": "JWT" // This token is only valid for ~2m from this point on
		}

+ Response 400 (application/json)

		{
			"message": "No body provided."
		}

+ Response 401 (application/json)

		{
			"message": "Invalid body provided."
		}

		{
			"message": "Invalid authorization."
		}

+ Response 403 (application/json)

		{
			"message": "This account has been deactivated."
		}

## Login 2FA [/login/mfa]

## Login 2FA [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer Temp2FAJWT

	+ Body

			{
				"token": "OPTCode",
			}

+ Response 200 (application/json)

		{
			"message": "Successfully logged in.",
			"token": "mfa.JWT",
			"apiKey": "your-api-key" // Only if requested via developer access
		}

+ Response 400 (application/json)

		{
			"message": "No body provided."
		}

+ Response 401 (application/json)

		{
			"message": "Invalid body provided."
		}

		{
			"message": "Invalid authorization."
		}

+ Response 403 (application/json)

		{
			"message": "This account has been disabled."
		}
