## Songs [/songs]

## Get Songs [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200 (application/json)

		{
			"message": "Successfully retrieved songs.",
			"songs": [
				{
					"albums": [
						"Märchen EP"
					],
					"albumsCover": [
						"Märchen-EP_cover.jpg"
					],
					"albumReleaseDate": [
						"1970-01-01T00:00:00.000Z"
					],
					"albumsSearchRomaji": [
						null
					],
					"albumsTrackNumber": [
						1
					],
					"albumsType": [
						1
					],
					"artists": [
						"Aiobahn"
					],
					"artistsId": [
						null
					],
					"artistsRomaji": [
						null
					],
					"artistsSearchROmaji": [
						null
					],
					"duration": 176,
					"enabled": true,
					"favorite": false,
					"groups": [],
					"groupsRomaji": [],
					"groupsSearchRomaji": [],
					"id": 1,
					"lastPlayed": "1970-01-01T00:00:00.000Z",
					"snippet": "1-1. ヘンゼルとグレーテルの森_snippet.mp3",
					"sources": [
						null
					],
					"sourcesRomaji": [
						null
					],
					"tags": [],
					"title": "ヘンゼルとグレーテルの森",
					"titleSearchRomaji": null,
					"uploaderUuid": "345c45aa-5h76-9zh4-6tr7-6tkl52rn5783",
					"uploaderUsername": "testuser",
					"uploaderDisplayName": "TestUser"
				},
				...
			]
		}

		{
			"message": "Successfully retrieved songs.",
			"songs": []
		}

## Upload Songs [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

	+ Body

			{
				"files": [
					{
						"type": 1,
						"albums": [
							"some-album"
						],
						"albumsRomaji": [
							"some-romaji-album"
						],
						"comment": "some-comment",
						"releaseDate": "some-ISO-releasedate",
						"songs": [
							"artists": [
								"some-artist"
							],
							"artistsRomaji: [
								"some-romaji-artist"
							],
							"artistGroup": false,
							"artistGroups": [],
							"artistGroupsRomaji": [],
							"characters": [
								"some-charcters"
							],
							"charactersRomaji": [
								"some-romaji-characters"
							],
							"file": "some-file-name",
							"source": "some-source",
							"sourceRomaji": "some-romaji-sorce"
							"title": "some-title",
							"titleRomaji": "some-romaji-title",
							"trackNumber": 1
						]
					}
				]
			}

+ Response 201 (application/json)

		{
			"message": "Successfully uploaded the file(s)."
		}

+ Response 400 (application/json)

		{
			"message": "No body provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

<!-- include(song/_username.apib) -->
