## Request [/requests/{id}]

+ Parameters
	+ id

## Post Request [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "No song found."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

		{
			"message": "All requests used for today."
		}

		{
			"message": "Song already queued."
		}

+ Response 500 (application/json)

		{
			"message": "Internal server error."
		}

## Delete Request [DELETE]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "No request found."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 500 (application/json)

		{
			"message": "Internal server error."
		}
