## User Songs [/songs/{username}/uploads]

+ Parameters
	+ username

## Get Songs [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200 (application/json)

		{
			"message": "Successfully retrieved uploads.",
			"uploads": [
				{
					"albums": [
						{
							"name": "Märchen EP",
							"nameRomaji": null,
							"image": "Märchen-EP_cover.jpg",
							"releaseDate": "1970-01-01T00:00:00.000Z"
						},
						...
					],
					"artists": [
						{
							"name": "Aiobahn",
							"nameRomaji": null,
							"image": null
						},
						...
					],
					"duration": 176,
					"groups": [],
					"id": 1,
					"lastPlayed": "1970-01-01T00:00:00.000Z",
					"source": [],
					"title": "ヘンゼルとグレーテルの森",
					"titleRomaji": null,
					"titleSearchRomaji: null
					"uploader": {
						"uuid": "345c45aa-5h76-9zh4-6tr7-6tkl52rn5783",
						"username": "testuser",
						"displayName": "TestUser"
					}
				},
				...
			]
		}

		{
			"message": "This user does not have any uploads."
			"uploads": []
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "Not a valid username."
		}

+ Response 404 (application/json)

		{
			"message": "No user found."
		}
