## Favorite [/favorites/{username}]

+ Parameters
	+ username

## Get Favorites [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 200

		{
			"message": "Successfully retrieved favorites.",
			"favorites": [
				{
					"albums": [
						{
							"name": "Märchen EP",
							"nameRomaji": null,
							"image": "Märchen-EP_cover.jpg",
							"releaseDate": "1970-01-01T00:00:00.000Z"
						},
						...
					],
					"artists": [
						{
							"name": "Aiobahn",
							"nameRomaji": null,
							"image": null
						},
						...
					],
					"duration": 176,
					"groups": [],
					"id": 1,
					"lastPlayed": "1970-01-01T00:00:00.000Z",
					"notes": null,
					"source": [],
					"tags": [],
					"title": "ヘンゼルとグレーテルの森",
					"uploader": {
						"uuid": ,
						"username": "testuser",
						"displayName": "TestUser"
					}
				},
				...
			]
		}

		{
			"message": "This user does not have any favorites.",
			"favorites": []
		}

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

		{
			"message": "Not a valid username."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 404 (application/json)

		{
			"message": "No user found."
		}
