## Favorite [/favorites/{id}]

+ Parameters
	+ id

## Add Favorite [POST]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 404 (application/json)

		{
			"message": "No song found."
		}

## Remove Favorite [DELETE]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json
			Authorization: Bearer JWT

+ Response 204

+ Response 400 (application/json)

		{
			"message": "No params provided."
		}

		{
			"message": "Invalid params provided."
		}

+ Response 403 (application/json)

		{
			"message": "Not authorized."
		}

+ Response 404 (application/json)

		{
			"message": "No song found."
		}

		{
			"message": "No favorite found."
		}
