# Home [/]

## Base route [GET]

+ Request (application/json)

	+ Headers

			Accept: application/vnd.listen.v4+json

+ Response 200 (application/json)

		{
			"message": "Welcome to Listen.moe! THE best J-POP radio."
		}
